### ISSUE TITLE
problem compiling on ubuntu 20.04

### ISSUE THREAD

**Issue by jdfrankland** [flueke/mvme#1]
Dear Florian,
On an up-to-date Ubuntu 20.04 with the latest version of dev branch I got the following error when trying to compile. Can you help me please?
Cheers
John

```
[ 96%] Linking CXX executable ../dev_data_filter_edit
[ 96%] Linking CXX executable ../dev_sis3153_read_raw_buffers_file
/usr/bin/ld: ../libmvme_core.so: undefined reference to `mesytec::mvme_mvlc::MVLC_VMEController::vmeMBLTSwapped(unsigned int, unsigned short, QVector<unsigned int>*)'
/usr/bin/ld: ../libmvme_core.so: undefined reference to `mesytec::mvme_mvlc::MVLC_VMEController::staticMetaObject'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/vme_script_checker.dir/build.make:112: vme_script_checker] Error 1
make[1]: *** [CMakeFiles/Makefile2:3026: src/CMakeFiles/vme_script_checker.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

Here are the exact steps I did:

```
git clone https://github.com/flueke/mvme.git
cd mvme && git checkout dev
git modules init && git modules update
cd .. && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ../mvme
make -j8
```
The output of cmake is below. 

`-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GIT_VERSION=1.0.1-324-g95c82119
-- GIT_VERSION_SHORT=1.0.1-324
-- GIT_VERSION_TAG=1.0.1
-- GIT_BRANCH=dev
-- GIT_VERSION=0.0.0-264-gf527993
-- GIT_VERSION_SHORT=0.0.0-264
-- GIT_VERSION_TAG=0.0.0
-- GIT_BRANCH=dev
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using CMake version 3.16.3
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Using ZLIB 1.2.11
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - found
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Using Iconv
-- Signing not supported when encryption is disabled
-- The following features have been enabled:

 * MZ_ZLIB, Enables ZLIB compression

-- The following features have been disabled:

 * MZ_COMPAT, Enables compatibility layer
 * MZ_BZIP2, Enables BZIP2 compression
 * MZ_LZMA, Enables LZMA compression
 * MZ_PKCRYPT, Enables PKWARE traditional encryption
 * MZ_WZAES, Enables WinZIP AES encryption
 * MZ_LIBCOMP, Enables Apple compression
 * MZ_OPENSSL, Enables OpenSSL for encryption
 * MZ_BRG, Enables Brian Gladman's encryption library
 * MZ_SIGNING, Enables zip signing support
 * MZ_COMPRESS_ONLY, Only support compression
 * MZ_DECOMPRESS_ONLY, Only support decompression
 * MZ_BUILD_TEST, Builds minizip test executable
 * MZ_BUILD_UNIT_TEST, Builds minizip unit test project
 * MZ_BUILD_FUZZ_TEST, Builds minizip fuzzer executables
 * MZ_CODE_COVERAGE, Builds with code coverage flags

-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Performing Test CFLAG_Wextra
-- Performing Test CFLAG_Wextra - Success
-- Performing Test CFLAG_Wundef
-- Performing Test CFLAG_Wundef - Success
-- Performing Test CFLAG_Wcast_qual
-- Performing Test CFLAG_Wcast_qual - Success
-- Performing Test CFLAG_Wcast_align
-- Performing Test CFLAG_Wcast_align - Success
-- Performing Test CFLAG_Wshadow
-- Performing Test CFLAG_Wshadow - Success
-- Performing Test CFLAG_Wswitch_enum
-- Performing Test CFLAG_Wswitch_enum - Success
-- Performing Test CFLAG_Wdeclaration_after_statement
-- Performing Test CFLAG_Wdeclaration_after_statement - Success
-- Performing Test CFLAG_Wstrict_prototypes
-- Performing Test CFLAG_Wstrict_prototypes - Success
-- Performing Test CFLAG_Wpointer_arith
-- Performing Test CFLAG_Wpointer_arith - Success
-- Performing Test CFLAG_W4
-- Performing Test CFLAG_W4 - Failed
-- Version: 6.2.1
-- Build type: Release
-- CXX_STANDARD: 14
-- Performing Test has_std_14_flag
-- Performing Test has_std_14_flag - Success
-- Performing Test has_std_1y_flag
-- Performing Test has_std_1y_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Required features: cxx_variadic_templates
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Build spdlog: 1.7.0
-- Build type: Release
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Using QUAZIP_INCLUDE_DIR=/usr/include/quazip
-- Using QUAZIP_QT5=/usr/lib/x86_64-linux-gnu/libquazip5.so
-- Using QWT_INCLUDE_DIR=/usr/include/qwt
-- Using QWT_LIBRARY=/usr/lib/libqwt-qt5.so
-- Using LIBUSB_LIBRARY=/usr/lib/x86_64-linux-gnu/libusb.so
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")  
-- Found boost for mvme in /usr/include
-- Found boost for liba2 in /usr/include
-- Found zlib for liba2 in /usr/include
-- CMAKE_BUILD_TYPE=Release
-- CMAKE_CXX_FLAGS=
-- CMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG
-- Configuring done
-- Generating done
`

**Comment by jdfrankland** [comment]
For information: I have exactly the same error with the master branch.
J

**Comment by flueke** [comment]
Hello John,
this should be fixed in the latest revisions of both branches. There where some shared library dependency issues which for
some reason did not cause problems on my dev system.
Regards
Florian

**Comment by flueke** [comment]
Closing as it should be fixed.

**Comment by flueke** [comment]
Closing as it should be fixed by now.
