### ISSUE TITLE
Issue while pulling submodules

### ISSUE THREAD

**Issue by alemasson** [flueke/mvme#3]
Hello,

While trying to compile mvme software(main branch), we faced the issue in pulling the submodules while following the instructions.
Bellow is the error namely on qgv :

git submodule update --init
Submodule 'external/mesytec-mvlc' (https://github.com/flueke/mesytec-mvlc.git) registered for path 'external/mesytec-mvlc'
Submodule 'external/qgv' (https://github.com/flueke/qgv.git) registered for path 'external/qgv'
Cloning into '/home/pista/Softs/mvme_org/mvme/external/mesytec-mvlc'...
Cloning into '/home/pista/Softs/mvme_org/mvme/external/qgv'...
fatal: remote error: upload-pack: not our ref ff40091a65f5b514a8cd9d9c6ce58ee57f32f34f
fatal: Fetched in submodule path 'external/mesytec-mvlc', but it did not contain ff40091a65f5b514a8cd9d9c6ce58ee57f32f34f. Direct fetching of that commit failed.
fatal: 

Can you help us ?
With best regards,
Antoine (and John F @GANIL !)

**Comment by flueke** [comment]
Oops, I forgot to push the latest mesytec-mvlc lib changes. It's fixed now.
