### ISSUE TITLE
Problem with file export sink erasing output files

### ISSUE THREAD

**Issue by wvonseeg** [flueke/mvme#8]
Hi Florian,

I am having an issue on mvme 1.10.3, running on Ubuntu 23.10.

I am replaying list files through the analysis with a file export sink using the listfile browser. I replay the listfile just fine and can see the compressed output file in my exports folder, but when I double-click on another file to run through the analysis, the output file that I just created is empty and reads as 0 bytes in the filesystem.  I have managed to save the file from being deleted only by closing mvme or by copying the file out of the export folder before opening a new listfile.  Closing the listfile or selecting another listfile erases the output file. I am using the Indexed/Sparse format with zlib compression if that helps.

**Comment by flueke** [comment]
Thank you for reporting this issue. The bug is fixed in [v1.10.4](https://github.com/flueke/mvme/releases/tag/v1.10.4). New packages are available on our website.
